version: "3.5"
services:
  deploy:
    image: doxerv
    build:
        context: .
        dockerfile: ./Dockerfile
    environment:
      DATA_DIR: /templating-data/
      TEMPLATE_DIRECTORY: /templating-data/templates/
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      AUTH_SERVER: ${AUTH_SERVER}
      AUTH_SERVER_ORIGIN: ${AUTH_SERVER_ORIGIN} # optional
      CLIENT_ID: ${CLIENT_ID}
      S3_BUCKET: ${S3_BUCKET}
      POSTGRES_VER: ${POSTGRES_VER:-12.1}
      SWAGGER_AUTH_CLIENT: ${SWAGGER_AUTH_CLIENT} # optional
      SWAGGER_AUTH_CLIENT_SECRET: ${SWAGGER_AUTH_CLIENT_SECRET} # optional
      SWAGGER_AUTH_SCOPE: ${SWAGGER_AUTH_SCOPE} # optional
    volumes:
      - ${DATA_DIR}/aws:/root/.aws

