version: "3.5"
services:
  database:
    build:
      dockerfile: docker/postgres.Dockerfile
      context: .
      args:
        pg_ver: ${POSTGRES_VER}
    image: postgres-templating
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/db:/data/db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /data/db/
    ports:
      - 127.0.0.1:5455:5432

  auth:
    image: jboss/keycloak:8.0.1
    command:
      - "-b 0.0.0.0"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: pass
      PROXY_ADDRESS_FORWARDING: ${KEYCLOAK_PROXY_ALLOWED:-false}
    restart: unless-stopped
    ports:
      - 8787:8080