version: "3.5"
services:
  templating:
    image: templating
    build:
        context: .
        dockerfile: ./Dockerfile
    environment:
      DATA_DIR: /templating-data/
      TEMPLATE_DIRECTORY: /templating-data/templates/
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      S3_BUCKET: ${S3_BUCKET}
      WORKER_CLASS: "egg:meinheld#gunicorn_worker"
    volumes:
      - ${DATA_DIR}/aws:/root/.aws
    ports:
      - 5000:80