services:
  plato-api:
    image: plato-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATA_DIR: /plato-data/
      TEMPLATE_DIRECTORY: /plato-data/templates/
      TEMPLATE_DIRECTORY_NAME: ${TEMPLATE_DIRECTORY_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      S3_BUCKET: ${S3_BUCKET}
      S3_TEMPLATE_DIR: ${S3_TEMPLATE_DIR}
      STORAGE_TYPE: ${STORAGE_TYPE}
      POSTGRES_VER: ${POSTGRES_VER}
    volumes:
      - ${DATA_DIR}/aws:/root/.aws
    ports:
      - "80:80"

  database:
    image: postgres:${POSTGRES_VER}
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/db:/data/db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /data/db/
    ports:
      - "5455:5432"
