services:
  plato-api:
    image: plato-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATA_DIR: /plato-data/
      IN_DOCKER: true
      DB_HOST: database
      DB_PORT: 5432
    env_file:
      - .env
    volumes:
      - ${DATA_DIR}/aws:/root/.aws
    ports:
      - "80:80"

  database:
    image: postgres:${POSTGRES_VER}
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/db:/data/db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /data/db/
    ports:
      - "5455:5432"
