[mypy]
disallow_untyped_defs = True
disallow_any_unimported = True
disallow_incomplete_defs = True

warn_redundant_casts = True
warn_unused_ignores = True
warn_unused_configs = True

no_implicit_optional = True
no_implicit_reexport = True

check_untyped_defs = True
show_error_codes = True
show_traceback = True

plugins = pydantic.mypy
exclude = tests

[mypy-num2words]
ignore_missing_imports = True

[mypy-google.cloud.*]
ignore_missing_imports = True

[mypy-weasyprint]
ignore_missing_imports = True

[mypy-accept_types]
ignore_missing_imports = True