[tool.poetry]
name = "micro-templating"
version = "0.0.1"
description = "Templating as a microservice"
authors = ["Tiago Santos <tiago.santos@vizidox.com>"]

[tool.poetry.dependencies]
python = "^3.6"

flasgger = "0.9.3"
flask = "1.1.1"
Flask-Cors="3.0.8"
uWSGI="2.0.18"

# auth
python-jose="3.0.1"

# settings
python-dotenv="0.10.3"
tomlkit="0.5.8"

# Database
SQLAlchemy = {version="1.3.11", extras=["postgresql_psycopg2binary"]}


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
