# Required metadata
sonar.projectName=plato
sonar.projectKey=Morphotech_plato
sonar.organization=morphotech

# Comma-separated paths to directories with sources (required)
sonar.sources=app/
sonar.tests=tests/

# Language
sonar.language=python
# Encoding of sources files
sonar.sourceEncoding=UTF-8

# Python settings
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.13
