[tox]
envlist =
    py313,
    mypy,
    ruff,
    alembic

isolated_build = True
skipsdist = true

[testenv]
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install
commands =
    poetry run coverage erase
    poetry run coverage run -m pytest
    poetry run coverage report --omit=tests/*

[testenv:mypy]
deps = mypy
commands =
    poetry run mypy app

[testenv:ruff]
commands =
    poetry run ruff check app tests

[testenv:alembic]
allowlist_externals =
    poetry
    sh
commands =
    sh ./check_alembic_heads.sh

[tox:.package]
# note tox will use the same python version as under what tox is installed to package
# so unless this is python 3 you can require a given python version for the packaging
# environment via the basepython key
basepython = python3
