version: "3.5"
services:
  auth:
    image: jboss/keycloak:8.0.1
    volumes:
      - ./micro-templating-keycloak-realm.json:/opt/jboss/keycloak/realm.json
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/realm.json"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: pass
      PROXY_ADDRESS_FORWARDING: "true"
    restart: unless-stopped

  deploy:
    environment:
      AUTH_SERVER: http://auth:8080/auth/realms/micro-keycloak
      AUTH_SERVER_ORIGIN: http://${HOSTNAME}/auth/reams/micro-keycloak
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deploy.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=mytlschallenge"

  traefik:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      #- "--certificatesresolvers.mytlschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.mytlschallenge.acme.email=dev@vizidox.com"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"

    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"