version: "3.5"
services:
  auth:
    image: jboss/keycloak:8.0.1
    volumes:
      - ./micro-templating-keycloak-realm.json:/opt/jboss/keycloak/realm.json
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/realm.json"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: pass
      PROXY_ADDRESS_FORWARDING: ${KEYCLOAK_PROXY_ALLOWED:-false}
    restart: unless-stopped
    ports:
      - 8787:8080

  deploy:
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      AUTH_SERVER: http://auth:8080/auth/realms/micro-keycloak
      AUTH_SERVER_ORIGIN: http://${HOSTNAME}/auth/realms/micro-keycloak